name: GluA2
channels:
  - conda-forge
  - defaults
dependencies:
  - python == 3.10
  - dataclasses == 0.8
  - matplotlib == 3.10.7
  - notebook == 7.4.7
  - numpy == 1.23.5
  - pandas == 1.5.3
  - pip == 25.3
  - scikit-image == 0.24.0
  - scipy == 1.10.1
  - seaborn == 0.13.2
  - shapely == 2.1.2
  - statsmodels == 0.14.5
  - scikit-posthocs == 0.11.4
  - pingouin == 0.5.5
  - git == 2.51.2
  - pip:
    - allensdk == 2.16.2
    - opencv-python
    - black == 25.11.0
    - rasterio == 1.3.11
    - -e.